backcast_loss_ratio: 0.0
context_length: 60
dropout: 0.1
expansion_coefficient_lengths:
- 32
- 32
- 32
learning_rate: 0.01
log_gradient_flow: false
log_interval: -1
log_val_interval: null
monotone_constaints: {}
num_block_layers:
- 4
- 4
- 4
num_blocks:
- 3
- 3
- 3
optimizer: Ranger
optimizer_params: null
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f4
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    CviCQg==
  max_length: null
  method: standard
  method_kwargs: {}
  scale_: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    3GjSQA==
  transformation: relu
prediction_length: 30
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 10
reduce_on_plateau_reduction: 2.0
sharing: false
stack_types:
- generic
- generic
- generic
weight_decay: 0.001
widths:
- 512
- 512
- 512
